name: Run Scripts Automatically

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Menjalankan setiap hari pada pukul 00:00 UTC

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Node.js Dependencies
      run: npm install
      working-directory: .

    - name: Run JavaScript Script
      run: node grassproxy.js

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Python Dependencies
      run: pip install -r requirements.txt

    - name: Run Python Script
      run: python grass.py

